### ISSUE TITLE
simplify/enhance ADX/DMI indicator

### ISSUE THREAD

**Issue by abzif** [ta4j/ta4j#100]
Simplify ADX/DMI computations using MMA indicator. Some intermediate helper classes would be not necessary.

Add xls testing

Allow two-argument ADX (in example ADX(14,8)). It allows independent smoothing of DI and ADX. Of course keep one argument ADX. ADX(14) = ADX(14, 14)

Rename current classes to more common names: AverageDirectionalMovementIndicator to ADXIndicator, DirectionalMovementMinusIndicator to MinusDIIndicator etc

I can help with it and implement the changes.

**Comment by nimo23** [comment]
Cool. This would be great! Thanks. 

_By the way: Please move the MMA indicator from "helper"-package to the package "ta4j.org.core.indicators"._

**Comment by abzif** [comment]
I consider MMA to be helper indicator but if you think it deserves promotion - no problem with moving it up.

**Comment by nimo23** [comment]
yes, because MMA is in fact a moving average like ema, sma and all those are within global indicator-package.

_In a future release, we consider to give it more structure (for example, moving all moving averages to a package "org.ta4j.core.indicators.ma" and all oscillators to a package "org.ta4j.core.indicators.oscillator")._

**Comment by team172011** [comment]
#111   merged
