### ISSUE TITLE
AverageReturnPerBarCriterion: formula

### ISSUE THREAD

**Issue by nimo23** [ta4j/ta4j#1090]
Despite the fact that `AverageReturnPerBarCriterion` includes the `ReturnCriterion` (**with base**) which seems to be a bug (because the `AverageReturnPerBar` implicitly inlcudes 100% and assumes that it's a profit, which is not), I have the following question according the formula used for this indicator:

`AverageReturnPerBar = pow(GrossReturn, 1 / bars)`

Why `pow`? Why not only `GrossReturn/bars` ?

**Comment by phong-phuong** [comment]
No, we can't simply divide the percent profit by the number of bars, as this does not take into the affect of compounding.
The fractional use of power was used to effectively "undo" the power of compounding in order to correctly calculate the return (on the assumption that ReturnCriterion is implemented correctly).

It is worthwhile to use to spreadsheet to see the effects of the formula to verify one's understanding.

The Return used includes the base as with everything in ta4j.

I think this is what the intended criterion was supposed to calculate:

`ExcessReturnPerBar = Math.pow(FinalReturnWithBase,, 1/NumOfBars) - Base`
where NumOfBars is the number of bars after the initial bar.

![image](https://github.com/ta4j/ta4j/assets/66398960/236f4b0a-de51-4dec-a8a5-7c94bf213658)

**Comment by phong-phuong** [comment]
To clarify further, the value returned by the current AverageReturnPerBarCriterion is actually the Return Multiple.
By that, I mean, if it returns a value of 2, this means the account is doubled every bar on average.

This is not to be confused with the absolute or dollar value.
