### ISSUE TITLE
Can you include transaction costs in a CashFlow series?

### ISSUE THREAD

**Issue by julianface** [ta4j/ta4j#118]
Hi there,

I know that you can calculate total transaction costs over a trading record but is it possible to reflect this in the CashFlow series? Currently when I'm plotting a trading strategy I can't find a way to show CashFlow less transaction fees along the way.

Thanks!

**Comment by team172011** [comment]
The CashFlow class does only calculate with the close price values of the underlying time series. To solve your issue you could extend the CashFlow class and override the **`CashFlow#calculates(Trade trade)`** function. There you can add your transaction costs to the formular (add to close price of entry index)

You issue shows an elementary design gap regarding instantiate an `Order` and maybe all `AnalysisCriterions`: 

- They are not based on the **order price** from corresponding `TradingRecord`, but on the **close price** from the `TimeSeries`. Therefore if the user creates orders thats buy/sell prices differ from close prices (e.g. because the user added transaction consts here) it will not be noticed in the criterions.
I have reopened #23 to fix this.

**Comment by team172011** [comment]
handled in #23
