### ISSUE TITLE
timeSeries with indicator in constructor

### ISSUE THREAD

**Issue by nimo23** [ta4j/ta4j#132]
"TimeSeries" in constructor is not needed, or?

```
/**
     * Constructor.
     * <p>
     * @param series the time series
     * @param maxValueIndicator the indicator for the maximum price (default {@link MaxPriceIndicator})
     * @param timeFrame the time frame
     */
    public AroonUpIndicator(TimeSeries series, Indicator<Decimal> maxValueIndicator, int timeFrame) {
        super(series);
        this.timeFrame = timeFrame;
        this.maxValueIndicator = maxValueIndicator;
```

So we can remove all indicators having timeSeries beside the the indicator, because all indicators implicitly provide the timeSeries-object. Or?

**Comment by team172011** [comment]
yes, thats looks redundant

**Comment by matetamas** [comment]
If you take a closer look, `AroonUpIndicator` and all the other Indicator implementations contain `getTimeSeries()` method, because it is inherited through `Indicator` interface. So setting the `TimeSeries` is obligatory. Only solution can be that you pass the passed `Indicator`'s `getTimeSeries()` method, so you can set the `TimeSeries` and prevent from setting `AroonUpIndicator` with a totally different `TimeSeries` instance.

Just to make things harder, there is another constructor:
```
/**
     * Default Constructor that is using the maximum price
     * <p>
     * @param series the time series
     * @param barCount the time frame
     */
    public AroonUpIndicator(TimeSeries series, int barCount) {
        this(series,new MaxPriceIndicator(series), barCount);
    }
```
This one uses the constructor you mentioned @nimo23.

I'm gonna try to find a solution for this, but I'm gonna show that in a commit, so it will be a lot more visible.
