### ISSUE TITLE
Implementing a MACD indicator based strategy

### ISSUE THREAD

**Issue by javieu** [ta4j/ta4j#157]
Hi, first of all, sorry for the (probably basic) question, but I have been unable to find the proper way to implement the script I am trying to code.

I am currently trading (manually, with no bots) altcoins in Binance exchange. I want to implement a simple bot which would just send bullish / bearish alerts, based on the typical bullish and bearish MACD Crossovers signals. I usually use this succesfully (combined with other indicators) on medium / long term trades, using the MACD indicator embedded in the Binance UI.

This implementation in Binance is the classic one:

MACD = EMA(12) - EMA(26)
Signal = EMA(9,MACD)

When the macd crosses up the signal -> bullish, cross down -> bearish.
I know this is simple, but I have not found the proper way to implement it. I have been checking the Ta4j example ta4jexamples.strategies.MovingMomentumStrategy, and it uses different indicators (at least some additional ones), and doing some backtesting I have found that it basically raises 0-1 alerts in 3 months (using 4H frame). And comparing it with the visual charts, it should have raised quite a few more.

I have then tried to simplify the implementation, basically trying to find the cross up:

                ClosePriceIndicator closePrice = new ClosePriceIndicator(series);
		MACDIndicator macd = new MACDIndicator(closePrice, 12, 26);
		EMAIndicator emaMacd = new EMAIndicator(macd, 9);
		Rule entryRule = new CrossedUpIndicatorRule(macd, emaMacd);
		Rule exitRule = new CrossedDownIndicatorRule(macd, emaMacd);
		return new BaseStrategy(entryRule, exitRule);

But then there are lots of alers (strategy.shouldEnter or shouldExit returns true), even when there has been no cross at all, comparing to the actual graphs.

Is there something wrong in my -basic strategy- implementation? 

Thanks in advance! (and sorry for my terrible english).

**Comment by team172011** [comment]
Hi @javieu,

i have added your strategy as example of my [charting application](https://github.com/team172011/TAcharting) and cannot reproduce your wrong signals. In general, your ema and macd indicator are very "close together", so that they will be highly vulnerable in sideways moving markets. For FB daily it looks like follows:
![grafik](https://user-images.githubusercontent.com/19409405/35249725-5bf7c48a-ffd3-11e7-83ad-7c40501b6a36.png)

All signals are correct. It is hard to comprehend because they are so close together, but i think the entry signal are just generated if macd crosses up emaMacd (red-green) and the exit signals are just generated if emaMacd crosses down macd (green-red):
![grafik](https://user-images.githubusercontent.com/19409405/35249900-2fa07d5e-ffd4-11e7-92c5-ddc2d9771504.png)

The implementation of ema and macd indicators looks fine, too. Maybe you have a different setup of the indicators in Binance UI?

**Comment by javieu** [comment]
Simon, you are totally right.

I was pretty sure that indicators were fine (and setup of indicators as well) since I coded the representation of the curves with JFreeChart and they were exactly the same as the Binance UI ones. And I have confirmed that the strategy is performing correctly; I have combined a manual check of the cross (checking previous and current values of both lines) with the shouldEnter() and shouldExit() method of the strategy, and indeed there is a 100% coincidence in the crosses. So everything is right; probably doing backtests I found too many signals during market phases like the current one, when both lines are, like you say, "close together" :)

So, thanks a lot for your quick response and sorry for the dumb question. At least I have learnt that it is not the same watching the graphs, when everything is so obvious (a cross is A CROSS), than coding a bot. I will add more indicators to avoid so many fake signals :)

Thanks again!
