### ISSUE TITLE
Extremely high memory usage when comparing (many) strategies

### ISSUE THREAD

**Issue by okieven** [ta4j/ta4j#258]
Hi, 

I want to compare different strategies (~50.000) with each other to find out which fits the best for me. I only invoke the entryRule.isSatisfied(index) on the strategies, I'm not using the build-in StrategyExceution engine, for this I implemented something that fits better to my purposes. I'm using the data of 30m Candles for 60 days, so 2880 data sets are iterated for each of the 50k strategies. The execution of the strategies takes a lot of time and eats tons of memory (up to 14GB, with 6 active threads in parallel), which is way too much in my opinion. 
Any ideas on how to optimize the memory usage or to speed up the execution? 

Thanks!

**Comment by team172011** [comment]
Can you please provide example code? Do you reuse indicators?

**Comment by okieven** [comment]
For sure, for example using a CCICorrection Strategy:
`private static Rule buildCCIEntryRule(TimeSeries series, int timeFrame, Decimal entry) {
    final CCIIndicator cci = new CCIIndicator(series, timeFrame);
    return new UnderIndicator(cci, entry);
}`
Where I use different combinations of timeFrame and entry. After creating a single entryRule, I build a BaseStrategy:
`private static Strategy buildBaseStrategy(String name, Rule entryRule, TimeSeries series) {
    return new BaseStrategy(name, entryRule, new StopGainRule(new ClosePriceIndicator(series), 
               Decimal.ZERO));
}`
I create this stupid exit rule just for avoiding NPE's.
The strategies are put into a Stack<Strategy> to take advantage oh stack.pop(), to delete them from memory after usage.
`while (strategies.size() > 0) {
    final Strategy strategy = strategies.pop();
}`
Then I iterate over the series of the strategy and only look if my entryRule is satisfied:
`for (int i = series.getBeginIndex(); i <= series.getEndIndex(); i++) {
    if (strategy.getEntryRule(i).isSatisfied) {
        ....
    }
}`
So for each combination of an Indicator I create a new object, I do not reuse them. What exactly do you mean with reusing them?

Thanks!

**Comment by team172011** [comment]
> Any ideas on how to optimize the memory usage or to speed up the execution?

Afaik you create 50k rules objects that hold 50k CCIIndicators (that creates SMA, MeanDeviatation and TypicalPriceIndicator) and 50k UnderIndicators and put them in 50k Strategies with additional StopGainRule and additional ClosePriceIndicator for each..

You could replace your exit rule (if it is useless) with a `BooleanRule` to reduce the size a little bit, but it will always stay powerfull because of the big amount of created objects. Also the size of your TimeSeries matters when talking about performance. Reuse Indicators like ClosePriceIndicator, Min/MaxPriceIndicator, or other Indicator thats calculated values are independent of the current Strategy. The calculated results will be cached by each indicator.

Like  @edlins mentioned, you do not have to initialize your Strategies all in one stack at the same time. Why not creating one Strategy, run it, analyse it and just store the important result and then create the next and so on? This can also be simultaneous in different threads
