### ISSUE TITLE
Is there a way in the calling to know which condition was satisfied (except that it was satisfied)

### ISSUE THREAD

**Issue by algotradersxyz** [ta4j/ta4j#261]
Hi,
           I was looking for a way to know which conditions out of the multiple conditions were satisfied ? I know we can enable the traceLog but that is for logger but in my calling code (where I am sending the email for Buy/Sell Signals) I need to put which conditions were satisfied and what were the calculated values ? Is there any in which this can be done. Looks like I may be missing something obvious.

Warm Regards,

**Comment by team172011** [comment]
Hi, 

this is a good question. You could store a reference to each of your rules, and if the strategy is satisfied at index x you could call the isSatisfied(x) function for each rule (again)

**Comment by edlins** [comment]
Just a thought: what if `isSatisfied()` returned a `Rule` or `null` (if not satisfied)?  The satisfying `Rule` could percolate up through the combining `Rules` like `AndRule` (return rule1 or rule2 or null).  Then the `Strategy.shouldEnter()` would know the satisfying rule and could similarly return that `Rule` or null instead of `boolean`.  Of course, multiple `Rules` could simultaneously trigger an entry, so maybe it would actually be `List<Rule>`.
