### ISSUE TITLE
Order.index for live trading

### ISSUE THREAD

**Issue by nabsha** [ta4j/ta4j#267]
Hi,

I am trying to identify the time when an Order was created. But in Live trading mode TimeSeries acts like a cyclic buffer when setMaximumBarCount is set and older bars are removed from the bar list. 
Which would mean that the bar index stored in Order may be pointing to a different entry in bar list.

I am not  able to understand why Order.java is referencing TimeSeries by index? 
Is TradingRecord only meant to be using in backtesting mode? 

Whats the best way to manage timestamp when the Order was created/executed?

**Comment by edlins** [comment]
> Is TradingRecord only meant to be using in backtesting mode?

My understanding is yes.

> Whats the best way to manage timestamp when the Order was created/executed?

Hmm, you might look at modifying `TimeSeriesManager.run()` since that's where you have both the `TimeSeries` and the `Strategy.shouldOperate()` calls.

**Comment by team172011** [comment]
> I am trying to identify the time when an Order was created.

If you use a restricted `TimeSeries` there is always the risk that your entry point will be replaced by new values (or rather its index can change). Why not using the  `strategy.shouldEnter(endIndex)` function and store all the relevatn informations (e.g. price and date) if it returns `true`?

**Comment by nabsha** [comment]
Hi Simon,

That is what I am doing now, I have added the ZonedDateTime to Order class and it is serving my purpose for now. IMHO, instead of storing price and time details in a separate data structure, TradingRecord is the right place to have such information.

I was expecting that TradingRecord should be serving as the trade history and in my solution, I want to persist it so history can survive restarts. It is important from audit point of view, but apparently current approach to TradingRecord is tilted towards backtesting only(although I dont know why it can serve both backtesting and live-trading purposes)

Is there any plan to consider such requirement in the near future?

**Comment by graph1zzlle** [comment]
Hello, I was also thinking about this, while wanting to implement trading record persistence so my trading engine can restart and restore its state.

I have the same issues with current TradingRecord implementation. It is not really easy to persist and rebuild TradingRecord state at the moment because it rely on `index`, which is wrong because the TimeSeries is a cyclic buffer, a timestamp instead of index would be probably better.

I don't have a problem using a different data structure to suit my needs but I am not agree TradingRecord should be used only for backtesting purpose. There is still a problem because we need a TradingRecord instance to use `strategy.shouldEnter(index, record)` & `strategy.shouldExit(index, record)`. These methods need a TradingRecord to return a correct value, rules such as `StopGainRule` rely on it.

**Comment by team172011** [comment]
I also think decoupling `TradingRecord` from `TimeSeries` would be a good next step, but like @graph1zzlle mentioned this step requiers a general redesign of the api. We can write this on the todo list of [release 0.13](https://github.com/ta4j/ta4j/milestone/6), it contains also some `TradingRecord` redesign ideas

**Comment by graph1zzlle** [comment]
@team172011 Maybe we could embed directly the candle data in the `Order` data structure, this will act as the context for this particular order. It would be immutable, with the downside of duplicating candle data (in TimeSeries, and in the Order).

**Comment by petoncle** [comment]
I agree that Order should not contain a TimeSeries's index.
However @graph1zzlle, I don't think the Order class should contain a Bar either. Imagine you're working with multiple time series of the same instrument, your order is relative to the instrument and not just to one particular time series.

Also, things get a bit confusing because of the naming of some of the classes:
- The Order class should be called Trade: typically an order is sent to the broker, then the broker processes the order, matches it with someone else's order and creates a trade.
- The Trade class should be called Position (or something similar) because it contains an entry and an exit, and a trade is not defined by an entry and an exit.

**Comment by nabsha** [comment]
Hi,

That is my understanding as well @petoncle. A bar represents an aggregated history of multiple trades, whereas an order is an individual to-be-trade. Also I think there is no relation between a TimeSeries and an Order at all. For instance, a TimeSeries is a function of Duration, which is totally irrelevant in the context of Order.

**Comment by edlins** [comment]
> an order is an individual to-be-trade

I generally agree but I've always disliked the usage and definition of `Trade`.  Fidelity considers a trade to be an action taken by a customer to attempt to create an `Order` which may or may not result in the opening of a (short or long) `Position`.  To them, a `trade()` isn't an object; it's a method representing a customer intention to create an `Order` or `null` (or `Exception`) if the request is invalid.  They have a "trade ticket" which is the customer's UI to enter, validate, and convey the proposed request to create an `Order`.  This directly conflicts with ta4j's definition of `Trade`, and I believe their usage to be industry standard but correct me if I'm wrong.

**Comment by nabsha** [comment]
Got your point @edlins 

I was thinking that we limit the scope of this ticket to how we can use TradingRecord in the live trading. Other refactoring issues, as mentioned by @edlins and @petoncle (which are equally valid) are handled separately.

What do you say?

**Comment by team172011** [comment]
@graph1zzlle we could extract an `Order` (@nabsha @edlins @petoncle agree that naming is improveable) interface with `getAssociatedBar()` function.
