### ISSUE TITLE
TradingRecord tracking an order that has not been filled?

### ISSUE THREAD

**Issue by stacksavings** [ta4j/ta4j#28]
Sorry if this is an obvious question, I have been reviewing how ta4j works lately and trying some coding and am a bit confused by something. It seems that you use the TradingRecord to enter a trade and then it will enter it right away. The problem is that, when using an API for a trading platform, the actual order may sit unfilled (open) for some time, as the price that the order was put in for may be lower than the current trading price (as tick data is usually out of date by some amount of time). Is there a way to account for this within a trading record so that it shows that an order has been placed but that a position is not actually currently held in that asset?

**Comment by team172011** [comment]
If i understand you right, you want to record an order that will be just placed if a specific price level was reached [limit order](http://www.investopedia.com/terms/l/limitorder.asp)?

At the moment the `TradingRecord` is designed just to record _real_ orders that were placed to buy/sell for the current price of the established security. So until such a time your order will be 'in held' you can record it, and if not you do not have to record it because it is not of importance

**Comment by stacksavings** [comment]
Yes that's basically what I mean.. ok that makes sense, I figure a way to track this then differently.

⁣Sent from BlueMail ​
