### ISSUE TITLE
Live Trading - start with empty candle

### ISSUE THREAD

**Issue by jurepetrovic** [ta4j/ta4j#289]
Hello guys, 

I'm having troubles in understanding how to start a new candle on period change. 

Let's say there is a new period start (either 1m, 30m or 1h). 
My procedure is to addBar(0.0, 0.0, 0.0, 0.0, 0.0) at the start of the period 
and then update it with addPrice() or addTrade() as wiki suggests. This is ok, but what if
there is no trade in the period? 

Then I get stuck with "0.0" candle which has serious impact on indicator values and 
is somehow not correct. What is your suggestion? 
Should I start (init) new candle with last candle's close data? 

Appreciate the help, 
Jure

**Comment by team172011** [comment]
Hello @jurepetrovic ,

There are [several approaches](https://www.kaggle.com/juejuewang/handle-missing-values-in-time-series-for-beginners) how to handle missing data and they will all influence the indicator results in different ways. The simplest approach would be to ignore the missing data (also not call the `addBar(...)`) function or to add a copy of the last available candle.
If you are in this situation repeatedly, I would recommend you to switch to a higher time level or rather use another security. You need a consistent data base to ensure that your indicators work correctly.

**Comment by jurepetrovic** [comment]
Thanks for the answer. 
Yes, I'm trying to copy the last values for now. 

However, the point is, I am creating a Bar at the start of the period and there is no way of knowing if a trade will happen during that period. We're talking low volume crypto altcoins here.

a)
If there is, addPrice() or addTrade() will update the Bar properly. 

b) if there is no trade until end of the period, I get a Bar will all zeroes in the series. Is there a way to check if the last bar was updated with addPrice()? Maybe a method like isBarUpdated()  or something? 
Or can I check if the close price of the last Bar differs from the initializiation value? 

Thank you again, 
Jure

**Comment by jurepetrovic** [comment]
Additionally, how can I replace a Bar in TimeSeries? 
Or remove it and add another one?

**Comment by team172011** [comment]
> Should I start (init) new candle with last candle's close data?

> I am creating a Bar at the start of the period and there is no way of knowing if a trade will happen during that period.


I do not know the structure of your program, but I would not recommend to create an "empty" bar with `addBar(0.0, 0.0, 0.0, 0.0, 0.0)` function call, or more specifically to add values to your time series that are not valid. Your open price will always stay 0.0, because that is the first value you have added. After calling `addPrice(10)` your last and highest price will be set to 10, but your openPrice and minPrice will wrongly stay at 0.0. You have to handle this check in your program code.

>  Is there a way to check if the last bar was updated with addPrice()? Maybe a method like isBarUpdated() or something?

I think this should be managed by your program (like above adding an "empty bar" does not make any sense)

> Additionally, how can I replace a Bar in TimeSeries? Or remove it and add another one?

With the `TimeSeries#getBar(index)` or the `TimeSeries#getBarData()` function you can get a reference to a specific `Bar ` or the internal ArrayList of `Bars`. I would not recommend to modify the internal ArrayList because it would break invariants of `BaseTimeSeries`. Maybe you could write and use your own implementation of the `Bar` interface or extending the `BaseBar` class and adding setter functions for the HLOC data.

**Comment by jurepetrovic** [comment]
Thank you for your help. Will try to build my program around those concepts. 

1) 
Open new candle only on first trade in the period. 

2) 
If no trade in the whole period, create new candle from the last close, where o=h=l=c=last.close

3) 
Good idea to extend BaseBar. This way I can include metadata if the candle was "opened" or not.

**Comment by jurepetrovic** [comment]
I'm still a bit confused.
From what I see, addPrice() DOES set open price if null. see attached pic.

On the ta4j-wiki you have example where interperiodic updates use addPrice() method. 
This means that last bar is created before candle end. When should this candle be created then? 
At the start of period? 

<img width="291" alt="capture" src="https://user-images.githubusercontent.com/35005863/42220507-700499dc-7ecf-11e8-900f-25e649721a4e.PNG">

<img width="650" alt="capture2" src="https://user-images.githubusercontent.com/35005863/42220539-8e47e5fc-7ecf-11e8-8524-14ee743aabd8.PNG">

**Comment by team172011** [comment]
> From what I see, addPrice() DOES set open price if null.

yes if `null` but not if `0.0` like you do in your procedure.

> This means that last bar is created before candle end. When should this candle be created then?

If I understand you right, I think you should create a new bar if you receive tick/price data the first time in that period.

**Comment by jurepetrovic** [comment]
Thanks for clarification. I was thinking in that direction. 

There is another design decision that seems a bit weird to me. It seems that standard in finance is to label the candles with "beginTime" and duration (period). However, TA4J lists endTime as mandatory value in constructor. If we're creating candle during live trades, it seems more logical to me to instantiate new Bar with beginTime and not endTime, which has not happened yet. 

Is there any specific reasoning here, that I'm missing?

**Comment by team172011** [comment]
I am not if there is a "standard" way to describe the time frame of a candle. I have seen brokers and implementations that are using just start time and others that are using just end time. In ta4j you can use startTime, endTime and a duration if you want. endTime is mandatory because most indicators are based on a closePrice. You can imagine the end time as "last time" data has been added to the candle and you can update the end time every time you add new data to the candle.

**Comment by jurepetrovic** [comment]
That's quiet an idea and would be a good solution also.
Currently I use extended Bar with an "opened" field, which tells me if the bar was updated or not. 
I instantiate the bar itself always with a period's ending timestamp...
