### ISSUE TITLE
New Double Top/Double Bottom indicator should be added.

### ISSUE THREAD

**Issue by puneet739** [ta4j/ta4j#3]
I think doubletop/bottom indicator should be added. It gives a lot of positive or negative signal.

This can be taken as future enhancement.

https://github.com/mdeverdelhan/ta4j/issues/193

**Comment by team172011** [comment]
Hi @puneet739,

thanks for transfering your issue to the new repository. Like in the previous discussion i would say that ![this](http://stockcharts.com/school/doku.php?id=chart_school:chart_analysis:chart_patterns:double_bottom_reversal) is not an indicator nether some kind or rule. It can be categorized as a more complex ![chart pattern](http://stockcharts.com/school/doku.php?id=chart_school:chart_analysis:chart_patterns).

So far this library has implemented some simple candle stick patterns like ![three black crows indicator](http://www.investopedia.com/terms/t/three_black_crows.asp). Those patterns are easy to define and there is no discussion about parameters and area of application. For example for the **three black crows**:

> This pattern consists of three consecutive long-bodied candlesticks that have closed lower than the previous day with each session's open occurring within the body of the previous candle.

For the **Double Bottom Reversal** the user has to customize a lot of parameters and other settings depending on the underlying chart and depending on the users strategy. Because of that i am taking the view that **complex chart pattern** are **not in the scope** of this library because their structure is located "at a level higher" than the structure of indicators, rules and simple candlestick patterns. 

Maybe the ![ta4j](https://github.com/ta4j) organization could start other projects for strategies and patterns like ![here](https://github.com/team172011/ta4j-strategies) where your issue could be helpfull.

**Comment by dpalic** [comment]
hi together,
I have also reread the discussion. I think the let me name it "multi-top" or "multi-bottom" is a chart-pattern. So if it is a naming issue, we could go on with this naming.
In my opinion having chart pattern recognitions would be a good addition to the lib.
It is somehow combined to head and shoulder recognition.

Maybe we could first try to fiddle out what params are needed for the recognition?
afaik the params are:

* time interval in time (e.g. in minutes, hours, ...) or in amount of ticks (e.g. 100x 5mins, 15mins, 1h, ...)
* absolute or percentage variance between the open/close values of the ticks
* the amount of tops or bottoms to detect
* anything else?

@puneet739 are you willing to contribute that code? You are pretty welcome!

**Comment by team172011** [comment]
I think:
- interval time should be always amount of ticks, because the structure of the lib is based on tick indices
- variance between open and close should always be percentage

In my view the questions are:
- how to use this indicator-pattern? Should it return just true or false if the pattern was detected?
- how to define the time frame e.g between two local maximums to avoid false signals from simple fluctuations?
- how to handle all the tolerance between min and max and between two max or mins?

**Comment by dpalic** [comment]
@team172011  "variance between open and close should always be percentage", why should it always be percentage? I prefer to leave the choice on user/developer side.

regarding "how to use this indicator-pattern?" also here I would return the found ticks. Means if my result is a empty Collection => i can add a convenience overloaded method to return true.

"how to define the time frame" now getting your point why you rejected it first. If we search also on local min/maxima it will get more tricky. Usually I am personally only interested in the latest min/maxima or mutli tops/bottoms. So this could be a restriction which helps?

"how to handle all the tolerance between min and max" do you mean the variance beween two tops or two bottom ticks?

**Comment by puneet739** [comment]
@dpalic i would definately like to take this further.

**Comment by dpalic** [comment]
@puneet739 great, let us know how we can support you on the contribution. 
Even if the discussion is not finalized internally, I would say this is a chart pattern recognition and not really a indicator. So we are not clean on the naming but "names are sound and smoke". So we can easily decide later if we name it as indicator or as chart pattern recognition

**Comment by puneet739** [comment]
@dpalic  perfect. Naming wont be very much required here. I haves some below points 

1) time interval in time (e.g. in minutes, hours, ...) or in amount of ticks (e.g. 100x 5mins, 15mins, 1h, ...)
1) I think we should consider this in ticks. Ticks can be hourly or daily depening upon dev choice. 


2) absolute or percentage variance between the open/close values of the ticks
2) We should work on percentage variance. 


3) the amount of tops or bottoms to detect
3) This is something i have doubt on. How shall i determine the size or double top that too in suedo code implimention. Kindly suggest.

**Comment by dpalic** [comment]
regarding your points I do not understand some facts, could you elaborate?

"3. absolute or percentage variance between the open/close values of the ticks"
what does this mean? why do you need a variance between open/close ticks? Afaik you need to see either based on all open or based on all close values the bottoms or the tops

"4. We should work on percentage variance."
fully unclear in combination to the 3.

"6. This is something i have doubt on. How shall i determine the size or double top that too in suedo code implimention. Kindly suggest."
imagine if you would do it manually. A good explaination: https://stackoverflow.com/questions/4050937/detect-local-minima-and-maxima-java
I would try to reuse apache commons: https://commons.apache.org/proper/commons-math/javadocs/api-3.0/org/apache/commons/math3/stat/StatUtils.html#max(double[],%20int,%20int) https://commons.apache.org/proper/commons-math/javadocs/api-3.0/org/apache/commons/math3/stat/StatUtils.html#min(double[],%20int,%20int)

**Comment by team172011** [comment]
> absolute or percentage variance between the open/close values of the ticks

@dpalic that was your question in the third post. I thought the length of a canlde is one criterium to detect this pattern. But i see that it is in most cases not necessary.

Befor talking about absolute and percentage variance we should determine what the indicator should return if the pattern is found and if not
- `true/false` -> this is compatible with the TimeSeriesManager and Strategy objetcs. But you do not have mor information than "one (very specific) pattern was found" or "one (very specific) patern was not found"
- `Decimal price` -> price of last breakout that completes the pattern. Same as with `true/false` values, but some more price informations.

- > also here I would return the found ticks. (from @dpalic  -> with this approach you have the most informations about the pattern, but it is absolut incompatible with TimeSeriesManger and Strategy objects because they expect boolean or Decimal values.

**Comment by puneet739** [comment]
I am stuck in this ticket and not able to proceed. Request anyone else to kindly see how this can be achieved.

**Comment by dpalic** [comment]
@puneet739 could you elaborate where you get stuck? Maybe we can support you?

**Comment by puneet739** [comment]
Can i do partial commits and push request? so that you can check the progress and correct wherever required?

I am stuck in identifying the time frame so that double top/bottom should be in equal interval.

**Comment by nimo23** [comment]
**Please look at "core.indicators.candles.*".** 

Such patterns described above could be implemented like the ones within the "core.indicators.candles" which always extends a CachedIndicator<Boolean> 
(the calculate() returns either **true** or **false**).

**Comment by nimo23** [comment]
I have created PositiveDivergence and NegativeDivergence as Rules instead of Indicators because it seems better than creating Indicators for that.

https://github.com/ta4j/ta4j/pull/69
