### ISSUE TITLE
ClassCastException: org.ta4j.core.num.BigDecimalNum cannot be cast to org.ta4j.core.num.PrecisionNum

### ISSUE THREAD

**Issue by dgosset** [ta4j/ta4j#313]
Since 05 sept, i had this classcast exception ! 

```
java.lang.ClassCastException: org.ta4j.core.num.BigDecimalNum cannot be cast to org.ta4j.core.num.PrecisionNum
at org.ta4j.core.num.PrecisionNum.plus(PrecisionNum.java:144)
at org.ta4j.core.BaseBar.addTrade(BaseBar.java:227)
at org.ta4j.core.BaseTimeSeries.addTrade(BaseTimeSeries.java:391)
```

I used
`series.addTrade(BigDecimalNum.valueOf(volume), BigDecimalNum.valueOf(bid));`

volume & bid are BigDecimal

On 4 sept, this code was OK.
So it looks like a bug from previous commit on 0.12-SNAPSHOT (public repo maven)

My local maven respo has many 0.12-SNAPSHOT :
This code WORKS with ta4j-core-0.12-SNAPSHOT.jar from 01/05/2018 (ta4j-core-0.12-20180428.131229-6)
This code is KO with ta4j-core-0.12-SNAPSHOT.jar from 05/09/2018 (ta4j-core-0.12-20180905.103425-7)

A rebuild?

I used BigDecimalNum which implements Num, and both class BaseTimeSeries & BaseBar have methods which are signed to accept classes which implements Num. Right?

[https://github.com/ta4j/ta4j/blob/develop/ta4j-core/src/main/java/org/ta4j/core/BaseTimeSeries.java](https://github.com/ta4j/ta4j/blob/develop/ta4j-core/src/main/java/org/ta4j/core/BaseTimeSeries.java)
391 public void addTrade(Num tradeVolume, Num tradePrice) {

[https://github.com/ta4j/ta4j/blob/develop/ta4j-core/src/main/java/org/ta4j/core/BaseBar.java](https://github.com/ta4j/ta4j/blob/develop/ta4j-core/src/main/java/org/ta4j/core/BaseBar.java)
224 public void addTrade(Num tradeVolume, Num tradePrice) {

**Comment by team172011** [comment]
I will also copy my current answer from #297:

> and both class `BaseTimeSeries` & `BaseBar `have methods which are signed to accept classes which implements Num. Right?

Once you have choose a `Num` implementation (`PrecisionNum`, `DoubleNum`) by creating a `TimeSeries` you have to stay at your choosen implementation. It is not possible to add a `DoubleNum` value to a `TimeSeries` or `Bar` that uses `PrecisionNum`. The simple reason for this behaviour is, that converting one `Num` implementation to another `Num` implementation can cause significant rounding issuses.

Furthermore the `BigDecimalNum` implementation will be deleted in #297, because it acts the same like the `PrecisionNum` implementation (both use `BigDecimal `as delegate).

I don't know your code, but I would recommend to use a `TimeSeries` with `PrecisionNum`. You can create it like:

`TimeSeries series = new BaseTimeSeries.SeriesBuilder().withNumTypeOf(PrecisionNum.class).build();`

subsequently you can do:

`series.addTrade(PrecisionNum.valueOf(volume), PrecisionNum.valueOf(bid));`
