### ISSUE TITLE
Introduce "Wilders Moving Average"

### ISSUE THREAD

**Issue by nimo23** [ta4j/ta4j#33]
Actually, ta4j have a few indicators from w.wilders:

- Average True Range (ATR)
- Directional Movement System (ADX/DI+/DI-)
- Relative Strength Index (RSI) 

ta4j uses a common moving average (SMA?) for these indicators. However, to be in accordance with the origin indicators, ta4j should normally use the "Wilder Moving Average" (http://www.macroption.com/atr-calculation/, http://www.macroption.com/atr-period/).

**So please introduce a new Moving Average Indicator "Wilder Moving Average" and make use of it within the wilders indicators (ATR, ADX, RSI, ..) of ta4j.**

(Maybe these indicators could have an optional constructor to put the type of moving average (SMA, EMA, WMA) into these indicators. For example, there are variations of ADX which uses the EMA internally.)

The indicators should be at least implemented with the **original** formula and normally this should be the default. However, I would let SMA for these indicators to be the default and would provide new constructors to put another moving average instead of the default.

**Comment by team172011** [comment]
> ta4j uses a common moving average (SMA?) for these indicators

What makes you think that? Have you taken a look at the implementation of the indicators or compared the results with other providers? 
Like in previous discussions i could only repeat:

- Directional Movement System (ADX/DI+/DI-) is already smoothed with wilders moving average
- There is a `TrueRageIndicator` that you can smooth or aggregate like you want and a `AverageTrueRangeIndicator` first look says it is smoothed with wilders moving average
- `RSIIndicator `is calculated in the way described [here](http://stockcharts.com/school/doku.php?st=rsi&id=chart_school:technical_indicators:relative_strength_index_rsi)

I therefor ask you, to study the relevant indicators and describe exactly your problem or bug. Also provide example data that shows the irregularities. Otherwise i have no capacity to check assumptions that are  based on supposition. [How to report a Bug](https://github.com/ta4j/ta4j/wiki/Found-a-bug%3F)

**Comment by team172011** [comment]
Additional there is the `SmoothedRSIIndicator`:
```
/**
 * Relative strength index indicator.
 * <p>
 * This calculation of RSI is based on accumulative moving average
 * as described in Wilder's original paper from 1978
 *
 * <p>See reference
 * <a href="http://stockcharts.com/school/doku.php?id=chart_school:technical_indicators:relative_strength_index_rsi">
 * RSI calculation</a>.
 *
 * @see RSIIndicator
 * @since 0.9
 */
```

**Comment by nimo23** [comment]
AverageTrueRangeIndicator uses ".dividedBy(nbPeriods)", so I assumed it would be a simple moving average, there is no WMAIndicator (WilderMovingAverage within indicator-package). However, I have overlooked SmoothedRSIIndicator..
