### ISSUE TITLE
Open source charts for ta4j? 

### ISSUE THREAD

**Issue by jansoren** [ta4j/ta4j#355]
Wich open source charts do we have out there for ta4j? 

With some dataporting react-stockcharts might be a solution:
- https://github.com/rrag/react-stockcharts
- http://rrag.github.io/stockcharts-demo/#

**Comment by graph1zzlle** [comment]
I am using https://github.com/highcharts/highcharts-react in my personal trading platform project, it works great :)

**Comment by graph1zzlle** [comment]
@jansoren What do you mean ? You can create any timeseries on the graph, so you can use the data generated by any ta4j indicators, candle series, etc... stockchart has also built-in support for several technical indicators. It is doing the job but the proposed api are really low-level. I am in the process of switching to tradingview.com/HTML5-stock-forex-bitcoin-charting-library/. The UI is really much more friendly, as you can select any technical indicators supported by trading view without having to compute and send back the data from the backend to the frontend.

**Comment by decebals** [comment]
@graph1zzlle 
I know about both charts: Highcharts (Stockchart) and Tradingview (Chart). I think that Tradingview has more features related to stock. My intention was to begin with Highcharts and to see the result. 
For me it is important the embeddable aspect. Highcharts is perfect embeddable and I feel that Tradingview is not (many references to Tradingview platform). Both are active maintained and this is very good.
And yes, Tradingview comes with many indicators by default, and that is good but I am not sure if these indicators use the same algorithm (from computational point of view) like in ta4j. I prefer also to have the possibility to add, in an easy mode, a new indicator in Tradingview.

> I am using https://github.com/highcharts/highcharts-react in my personal trading platform project, it works great 

Is it your platform public (open source)?
I ask you because I intend to develop a such platform using ta4j. I have experience in Java and open source (see my github profile, I am the creator of PF4J, Pippo, NextReports, ...) but I don't have enough knowleadge related to finance (stock, ...). I see some projects that integrate ta4j but, in my opinion, they are only isolated pieces, nothing complete, ready to use. In first step I want to create a personal assistant, to give me hints about when is a good time to sell or buy, to filter information for me, to decrease the spent time to find leads.
If you are aware about a such platform please say me. Also, if other people want to join me, I will happy to colaborate. I think that we can create a serious open source trading platform, configurable enough to satisfy any (or almost any) trading aspects/styles.

**Comment by graph1zzlle** [comment]
@decebals I am thinking about open-sourcing it before the end of the year. It is composed of a data collection service, a backtest engine & ui, a live trading engine. Technologies used are Akka, Scala & React. I am currently working on polishing the backtest ui but everything is already working and generating real trades on Binance. If other people are interested I can work to open-source it sooner.

**Comment by jansoren** [comment]
@graph1zzlle - If you open source it I would love to look into your setup :+1:
