### ISSUE TITLE
Wrong word used on Attributes in the BaseBar class

### ISSUE THREAD

**Issue by elbricksalazar** [ta4j/ta4j#446]
Hello everybody:

The attributes MaxPrice and MinPrice, they are not correct, names correct are High y Low, this is something very simple but sometimes confused when we are writing the code

regards

**Comment by team172011** [comment]
Hi @elbricksalazar 
in previous versions it has been called **high** and **low** and we renamed it to **max** and **min**. As far as I can see the names high and low are usually used and you are right. We should really think about renaming it back. Naming is always a difficult topic...

- https://en.wikipedia.org/wiki/Candlestick_chart
- https://www.investopedia.com/terms/b/bar.asp

**Comment by milczarekIT** [comment]
Hi
@team172011,  you are wrong. In previous versions it has been called **max** and **min** and we renamed it to **high** and **low**.
Probably @elbricksalazar is using released version or 'master' branch code. Due to low frequency he still see **min** and **max**.

This change was introduced almost 1 year ago and still is not released: https://github.com/ta4j/ta4j/pull/326

**Comment by team172011** [comment]
@milczarekIT yes i mixed it up: high and low refactoring has already been introduced on develop. Will be part of next realese #458
