### ISSUE TITLE
NaN result when not exists Maximum DrawDown   calculating Reward/Risk Ratio

### ISSUE THREAD

**Issue by elbricksalazar** [ta4j/ta4j#450]
For some strategies, the maximum DrawDown is equal to 0, this happens when all exchanges are winners. What is the appropriate value for these reward/risk relationship cases, since, the formula 

**Formula:** `totalProfit.calculate(series, tradingRecord).dividedBy(maxDrawdown.calculate(series,tradingRecord)); `
**Where:**  `maxDrawdown.calculate(series, tradingRecord))==0`
**Then:** The result is NaN

```
public class RewardRiskRatioCriterion extends AbstractAnalysisCriterion {

	private AnalysisCriterion totalProfit = new TotalProfitCriterion();

	private AnalysisCriterion maxDrawdown = new MaximumDrawdownCriterion();

	@Override
	public Num calculate(TimeSeries series, TradingRecord tradingRecord) {
		return totalProfit.calculate(series, tradingRecord).dividedBy(
				maxDrawdown.calculate(series, tradingRecord)); 
	}

```

**Comment by milczarekIT** [comment]
Hi @elbricksalazar 
Yes, a calculation is correct. When there is no drawdown Risk/Reward ratio is not available yet, so NaN is the correct value.

In a typical situation when you run backtest for a bigger data set there is no option for no drawdown because strategies with a 100% success rate do not exist.
Yes, it is possible to have no drawdown on a small data set or in live trading at the begging... but until first loss risk/reward ratio is not available.

I've just created PR (https://github.com/ta4j/ta4j/pull/465) with improvement for calculation: there is no sense to calculate total profit if there is no drawdown.

**Comment by team172011** [comment]
#465 merged
