### ISSUE TITLE
TradingRecord: rule.isSatisfied(tradingRecord) with splitted orders

### ISSUE THREAD

**Issue by nimo23** [ta4j/ta4j#487]
I have a question:

Some `rules` need a `tradingRecord` to get a valid `isSatisfied(tradingRecord)`.

Does these rules also work with splitted orders?

According to https://github.com/ta4j/ta4j/issues/466

> you could very well execute a buy order with a lot size of 3, and then a later execute a sell order of size 2, then later sell order size 1. 

**Does ta4j handles such scenarios within `rule.isSatisfied(tradingRecord)`?**

**Following example.** 

The **tradingRecord** has these orders:

```
Order 1: enter with volume=3 (enter signal comes from rule.isSatisfied(tradingRecord))
Order 2: exit with volume=2 (exit signal comes from rule.isSatisfied(tradingRecord))
(I am waiting for another exit with volume=1 as I could not close the whole position within "Order 2")
```

The exit for "Order 2" was triggered by `rule.isSatisfied(tradingRecord)`. What happens now? Does the tradingRecord propagate the needed exit `volume=1` to `rule.isSatisfied(tradingRecord)`? Does the rule know that there is another need for an exit?

**Comment by milczarekIT** [comment]
> 

> According to #466
> 
> > you could very well execute a buy order with a lot size of 3, and then a later execute a sell order of size 2, then later sell order size 1.

This is not supported by `BarSeriesManager`.
`BarSeriesManager` is very simply a strategy runner for very simply backtesting.
Described scenarios are of course possible with custom strategy runners.


> Does ta4j handles such scenarios within rule.isSatisfied(tradingRecord)?

`BarSeriesManager` does not allow to close position partially.

**Comment by nimo23** [comment]
@milczarekIT thanks for the answer.

Actually, users excepts that such scenarios described above already work. Not only because I can use someting like the following code which is actually valid and does not throw any errors:

```
// enter with volume=3
recorder.enter(endIndex, price, 3);
// enter with volume=2
recorder.exit(endIndex, price, 2);
```

Hence, it is a bug within BarSeriesManager which must be resolved to handle such orders.

**Comment by milczarekIT** [comment]
> Actually, users excepts that such scenarios described above already work.

They work but not with `BarSeriesManager`.

> // enter with volume=3
> recorder.enter(endIndex, price, 3);
> // exit with volume=2
> recorder.exit(endIndex, price, 2);

If you used this code, it means you are not using `BarSeriesManager`, because `BarSeriesManager` does not allow to exit with the different amount then enter amount.

> user waits for the next exit signal of volume=1 but no exit signal 

You are wrong. The next signal will occur. Of course not in `BarSeriesManager`, because here the whole position will be closed. But in your example, you are not using code from `BarSeriesManager`. 

See: https://ta4j.github.io/ta4j-wiki/Roadmap-and-Tasks.html
Here is following info
> Redesign of backtesting logic (buy/sell at any index, drop ‘just one open trade’ concept)

It is not a bug it is a current concept 'just one open trade'. It is a concept one open - one closed trade. There was an idea to drop this concept in 0.13, but I think it will be postponed.

**Comment by nimo23** [comment]
>You are wrong. The next signal will occur. 

So `shouldExit(i, tradingRecord) `and `shouldEnter(i, tradingRecord)` with a `tradingRecord` described above can handle closing position partially and does not miss an exit signal because of a partially closing position?

Good to know that this is on the roadmap.

**Comment by nimo23** [comment]
TradingRecord should also handle such cases:

```
recorder.enter(endIndex, price, 3);
recorder.exit(endIndex, price, 2);
recorder.exit(endIndex, price, 1);
recorder.enter(endIndex, price, 5);
recorder.enter(endIndex, price, 6);
recorder.enter(endIndex, price, 11);
```

**Comment by saulojg** [comment]
> `TradingRecord` should also handle such cases:
> 
> ```
> recorder.enter(endIndex, price, 3);
> recorder.exit(endIndex, price, 2);
> recorder.exit(endIndex, price, 1);
> recorder.enter(endIndex, price, 5);
> recorder.enter(endIndex, price, 6);
> recorder.exit(endIndex, price, 11);
> ```

I see two different cases here:

**Ability to close trades partially**
I'd say this is a much needed feature, since it's often common not to be able to close a trade on the first try. If I were to do this, I'd have `TradingRecord` split its trades just to avoid a major refactoring of existing `AnalysisCriterion` implementations.
IMHO this should be a default behavior.

**Ability to allow multiple trade entries**
At first glance, it looks kind of dangerous to take every entry signal. However, I think it has to be supported for these cases where you want to reach a certain position size. 
This should not be a default beahavior as it carries risk and also would probably break every existing (back)testing code out there.
While supporting this, It could help to have `TradingRecord` report the total amounts of its opening and closing orders.

**Comment by nimo23** [comment]
I think the best would be to have two kinds of tradingRecords in ta4j:

- `SingleTradingRecord` (the current BaseTradingRecord renamed)
- `MultiTradingRecord` (the TradingRecord which supports arbitrary enter and exits)

**Comment by chautrader** [comment]
I'm want to comment/propose here on **the ability to allow dual sided trade entries**
I'm not looking at partial trades here yet, although that also is an important feature.

The current BaseTradingRecord supports entries on 1 side only.  What would be nice are entries on both sides. Two options are:

1. modify existing TradingRecord to support entries on both sides OR
2. adding another TradingRecord type (which would be better named `DualSidedTradingRecord`). 
Both options need BarSeriesManager to be modified (and perhaps others?).

Current interface TradingRecord then needs new/modified methods imho that include the side:
- public boolean enter(int index, Num price, Num amount, **OrderType orderType**) 
- public void operate(int index, Num price, Num amount, **OrderType orderType**)

**Comment by nimo23** [comment]
closed in favor of of https://github.com/ta4j/ta4j/issues/755
