### ISSUE TITLE
Correct indentation for project

### ISSUE THREAD

**Issue by milczarekIT** [ta4j/ta4j#502]
Almost the whole project has a correct indentation: 4 spaces.

Unfortunately in the PR: https://github.com/ta4j/ta4j/pull/469 was introduced incorrect indentation. During this PR, I requested 2 times to revert insufficient changes, but it was ignored by @nimo23.
I would like to point to this issue for code reviewers - to take care of this too.
Fix reverting unexpected changes: https://github.com/ta4j/ta4j/pull/501

If it is not clear why 4 spaces should be used instead of tab character:

> A tab could be a different number of columns depending on your environment, but a space is always one column.

https://softwareengineering.stackexchange.com/questions/57/tabs-versus-spaces-what-is-the-proper-indentation-character-for-everything-in-e

And the additional article: https://stackoverflow.blog/2017/06/15/developers-use-spaces-make-money-use-tabs/

I will try to check if it can be configured in maven plugin for formatting/validation. Then it will be easier.

**Comment by nimo23** [comment]
>but it was ignored

Not intentionally, I corrected those classes to 4 spaces by github editor. However, we also have maven format plugin which should care of such things automatically. I already told you more than one time: Do not force people to adapt their code formatting preferences to this project. But you do not understand and your two links does only convince me more to use tabs instead of spaces.
