### ISSUE TITLE
Backtesting - Trade Entry

### ISSUE THREAD

**Issue by toriacht** [ta4j/ta4j#523]
I am trying to test my strategy, if my indicator crosses up an ema then enter, like so, and a crossed down to exit......:

```
  entryRule = new CrossedUpIndicatorRule(myIndicator,ema );
  exitRule = new CrossedDownIndicatorRule(myIndicator,ema);
```

I set up my test like so.........

```
BarSeriesManager seriesManager = new BarSeriesManager(testSeries);
TradingRecord tradingRecord = seriesManager.run(strategy, Order.OrderType.BUY);
```

However, the seriesManager enters a trade as soon as it sees a `CrossedDown`, not `CrossedUp`?
When running live it behaves correctly....

Any tips appreciated....

**Comment by team172011** [comment]
Hi @toriacht,

how do you create your strategy?

**Comment by robzsaunders** [comment]
I'm seeing similar behavior

My strategy that I'm using in other backtesting engines (pinescript/tradingview) are giving me the proper results.

For other strategies that use other rules, TV and TA4J are very similar (as they should be) but the crossedup/crosseddown rules are giving me inverted results. 

@team172011 or @nimo23 can you please investigate, I don't have the time to properly deep dive into this one. It feels like it's exporting the back test results backwards or something.

The long I have setup (CrossedUpIndicatorRule for entry, CrossedDownIndicatorRule exit) is giving me a negative result and the opposite for shorts is giving me good longs performance. Normally in long-only backtesting my long is positive and my short is negative.

For further reference, if I go into TV and put my same strategy in using ta.crossover instead of CrossedUpIndicatorRule and ta.crossunder for CrossedDownIndicatorRule, I get my intended results.

In TA4J I get **the exact same results but inversed, so my long strategy is reporting my shorts results in TV, and my short strategy is reporting my long strategy from TV**

It's only with these indicators in my current setup that I see this happen.
