### ISSUE TITLE
Criterion renames

### ISSUE THREAD

**Issue by kennethjor** [ta4j/ta4j#538]
I know this would be a major breaking change, but I feel like a lot of the names for the criterions in the analysis package have very confusing names. Rather than just submit a huge breaking change PR, I thought I'd bring it up first.

* `AverageProfitableTradesCriterion` - calculates the number of winning trades over the total number of trades. Rename to `WinningTradesRatioCriterion`?
* `AverageProfitCriterion` - calculates the return as a percentage per bar, defined at the `return^(1/bars)`. Rename to `AverageReturnPerBarCriterion`?
* `BuyAndHoldCriterion` - calculates the return of a buy-and-hold strategy. Rename to `BuyAndHoldReturnCriterion`?
* `RewardRiskRatioCriterion` - calculates [return over max drawdown](https://www.investopedia.com/terms/r/return-over-maximum-drawdown-romad.asp), which is what it's called. "Risk-reward ratio" could mean a number of things, including Sharpe Ratio. They both measure the risk-reward ratio. Rename to `ReturnOverMaxDrawdownCriterion` or `RomadCriterion`?
* `TotalProfitCriterion` - calculates the return ratio rather than the profit. Rename to `TotalReturnCriterion`?
* `TotalProfit2Criterion` - calculates the total profit. Rename to `TotalProfitCriterion`?

I think this would make the analysis package easier to use, as one doesn't have to read source code in order to understand what's going on.

**Comment by nimo23** [comment]
>have very confusing names

Yes, I am definitely the same opinion. As you see, naming classes and concepts is very important! I must admit that I also created a similar renaming scheme for a few of those criterions within my ta4j-codebase a few month ago. And I also wanted to prepare a PR for those renamings in future - but I reserved it as long as the other PRs/Issues (https://github.com/ta4j/ta4j/issues/476, https://github.com/ta4j/ta4j/issues/466) exist. You see, it is not easy to convince all people for that renamings, even for the obvious ones :)

But nevertheless, let's do that renamings. I think your suggested names are all better than the previous ones. 

But one little suggestion to be consistent: 
Either use for all `Ratio` criterions the suffix `Ratio` or the prefix `Avg`. For example, as you said, `TotalReturnCriterion` returns a ratio (= avg) rather than the profit, thus append the `Ratio`-suffix (or the prefix `Avg`). The same for all others: `AverageProfitableTradesCriterion` -> either `WinningTradesRatioCriterion` or `AvgWinningTradesCriterion`. Either use `Avg` or `Ratio` for all indicators to be consistent (for example: we actually say `AverageProfitCriterion`, thus according to be consistent we should either say `AverageProfitCriterion`, `AvgProfitCriterion` or `ProfitRatioCriterion`.

**Comment by kennethjor** [comment]
> As you see, naming classes and concepts is very important!

@nimo23 Let's not start here, as well :) Naming is important, let's just take each case as it comes.

I don't think `Ratio` and `Avg` can be applied to all cases. The word "ratio" describes something in relation  to something else. A `WinningTradesRatio` I would expect to give me `winning trades / losing trades`. I.e. the winning trade ratio is 2:1.

The word "average" implies some total divided out over some unit. An `AverageWinningTrades` I would expect to give me the average profit per winning trade, though the name doesn't clearly imply that.

FWIW, in my naming, what I was going for was to define "profit" as an absolute unit of "you make $100" and return to mean something relative like "you make 110% of your money back". I'm not hellbent on this either.

TBH there's a lot of inconsistent naming in the trading industry, hell, in the world! English itself is inconsistent. Rather than trying to apply The Perfect Naming, we should take whatever term is currently established in the world and just use that, even if it doesn't make 100% sense.

**Comment by nimo23** [comment]
Oh, yes. `Ratio` and `Avg` _are_ different kind of things, for example:
- Ratio = 1:4
- Avg = (2+3)/2

Wanted to say, the _class names_ of the criterions must explicitly use the term "Ratio" (suffix) or "Avg" (suffix or prefix?) , if they fall into one of those categories..a criterion which is a ratio should not be called avg and vice versa.

**Comment by nimo23** [comment]
>to define "profit" as an absolute unit of "you make $100" and return to mean something relative like "you make 110% of your money back".

If a criterion represents an absolute number (instead of a relative one), then it should have the suffix `Abs`.

Btw, instead of ProfitAndLoss, you can say PnL (which is the standard abbreviation). With this, you can also say RealizedPnL (this is what the Backtest actualy returns)..

**Comment by milczarekIT** [comment]
@kennethjor thumb up. I reviewed all your proposed names and it looks reasonable.

**Comment by team172011** [comment]
I agree with your suggestion @kennethjor and I also agree with @nimo23 in #466. The kind of how ta4j uses `Trade` and `Order` has been one of the most confusing things for me when I started using this lib. Especially because of
> there's a lot of inconsistent naming in the trading industry, hell, in the world!

In my opinion the renaming of #476 makes sense as well, but it is not worth the trouble of making again breaking changes. But if we agree with refactorings mentioned in #538, #466 I would also go for #476.

**Comment by kennethjor** [comment]
PR for this has been submitted, just in case you didn't notice :)

**Comment by nimo23** [comment]
There is a subtle difference between `Total` and `Gross`: 

Gross includes commissions, while `Net` does not. `Total` is ambiguous. 
So I adapt the names in https://github.com/ta4j/ta4j/pull/573.
