### ISSUE TITLE
CachedIndicator should be a wrapper indicator not in inheritance structure

### ISSUE THREAD

**Issue by GxtPerfectoM** [ta4j/ta4j#608]
Currently it looks like the CachedIndicator is causing problems in multi-thread mode.
In general you should not use the CachedIndicator in inheritance structure but instead offer it as a wrapper to other indicators (Delegator) and this will give the way to avoid using it if needed.

**Comment by nimo23** [comment]
@GxtPerfectoM would be nice if you can make a PR with your suggestion.

**Comment by johnthetireless** [comment]
Here is a naive "caching decorator" around Indicator<Num>.
You can adapt for <T> and change the caching policy as you see fit.

public interface NumericIndicator extends Indicator<Num> {
}

public class CachedNumericIndicator implements NumericIndicator {  

	private final List<Num> cache = new ArrayList<>();
	
	public CachedNumericIndicator(Indicator<Num> delegate) {
		super(delegate);
	}

	/*
	 * Simplistic implementation will probably suffice for most use cases.
	 * Replace or override if desired
	 */
	@Override
	public Num getValue(int index) {
		if ( index < cache.size() ) {
			return cache.get(index);
		}
		else {
			Num result = delegate.getValue(index);  
			cache.add(result);
			return result;
		}
	}
	
	@Override
	public Num numOf(Number number) {
		return delegate.numOf(number);
	}
	
	@Override
	public BarSeries getBarSeries() {
		return delegate.getBarSeries();
	}

}

**Comment by johnthetireless** [comment]
Generic types didn't copy/paste correctly.

**Comment by johnthetireless** [comment]
Caching 

There are 6-7 "helper" indicators like MedianPrice whose calculation is based solely of the price/volume data of a single bar. Caching the result of Open(i) + Close(i) / 2 seems questionable.

A larger set of higher-level indicators do the same, but they do arithmetic on values obtained from "child" indicators.
PlusDI(n) = MMA)n) / ATR(n) * 100, for example. I would be inclined to let this calculate each time without being cached.

I would really like to see caching removed from the Difference, Sum and other "arithmetic" indicators. They don't seem to be used much, but series arithmetic is a powerful concept. A(i) = B(i) + C(i) is very easy to code as an operation of 2 series.

**Comment by nimo23** [comment]
See https://github.com/ta4j/ta4j/issues/522#issuecomment-601354192

**Comment by nimo23** [comment]
There is always a tradeoff between re-calculation of indicator values (CPU) vs storing already calculated indicator values (Java heap). However, it's best to let the user decide which one to use, that means: If the user **disables the cache**, then indicator values are re-calculated on demand. If the user **enables the cache (default)**, then indicator values already calculated are taken from the cache. We should provide this option in ta4j to disable the cache.

**Comment by johnthetireless** [comment]
there are so many easy fixes that you or anyone could make to this library to  clean up the array allocations its boggles my mind...   in an afternoon you could cut out 25% of the wasted space that causes problems you don't have because you ado the right things....   yet you will comment on this, and draw false dependencies on it, waiting for someone else to come along and submit a magic fix to "turn caching off" which is not possible...  do something...  i am amazed at the attitude... someone points out a flaw and you tell them to submit a PR and it gets ignored or worse, attacked...  i suspect this issue will sit here while nobody does anything because they can't... the process is impossible... you are stuck with some very bad code in some places because no one will change it and no one can.. 

i wish you luck...  i am done

**Comment by nimo23** [comment]
>there are s**o many easy fixes** that you or anyone could make to this library to clean up the array allocations its boggles my mind..**you are stuck with some very bad code in some places**

@johnthetireless I think you didn't really understand the full point of caching. You can re-calculate if a value is not cached or cannot be found in the cache. But nevertheless, please tell us: what exact classes or methods in this project you are talking about? What kind of fixes for what code do you mean exatly?

In  general, it would help if you could get the facts straight in a constructive way so we know where (in the code) improvements can be made instead of blaming us in such a condescending way.

**Comment by johnthetireless** [comment]
Please don't tell me if don't understand.. well anything...  the title of your last issue "disable caching in BarSeriesManager#run" tells anyone you have no real insight into how the system works.  
"letting it go out of scope"  "yes, I guess that would work" tells anyone who reads it that you don't understand how Java works... setting things to null to clears caches?  I very much doubt you ever though not keeping your strategies in a list; no example to copy and paste.  But you are an "expert" so you could not tolerate me being right - and genuinely helpful.. 

I have listed places where things could be fixed on a couple of occasions and was basically told to do it myself.  I will not try to "help" you ever again.  What would you do, anyway?  Nothing.

**Comment by nimo23** [comment]
@johnthetireless This is just another example of where instead of addressing the issue, you're again distracting and being rude. Me and the community are here to help and spend time to make this project better. 

> there are so many easy fixes* that you or anyone could make to this library to clean up the array allocations its boggles my mind..you are stuck with some very bad code in some places

I asked you politly: "What kind of (the "so many easy") fixes for what code do you mean exactly?" And what are you doing? Bashing and again not answering any questions.

**Comment by nimo23** [comment]
Also explained here https://github.com/uniVocity/univocity-trader/issues/7#issuecomment-687837498

**Comment by TheCookieLab** [comment]
> there are so many easy fixes that you or anyone could make to this library to clean up the array allocations its boggles my mind... in an afternoon you could cut out 25% of the wasted space that causes problems you don't have because you ado the right things.... yet you will comment on this, and draw false dependencies on it, waiting for someone else to come along and submit a magic fix to "turn caching off" which is not possible... do something... i am amazed at the attitude... someone points out a flaw and you tell them to submit a PR and it gets ignored or worse, attacked... i suspect this issue will sit here while nobody does anything because they can't... the process is impossible... you are stuck with some very bad code in some places because no one will change it and no one can..
> 
> i wish you luck... i am done

I don't agree with @nimo23 often, but my God the entitlement and lack of self awareness from @johnthetireless here is astounding. 

Ta4j is open-source software. Again that's open. source. software. Do you know what that means?

@johnthetireless here you are enjoying the fruits of others' labor, saving time, effort, and potentially money, and instead appreciating how you're literally getting something for nothing, you demand others do even more, all without lifting a finger yourself.

> there are so many easy fixes that **you or anyone** could make to this library to clean up the array allocations its boggles my mind...

You do realize **anyone** includes you right? This would be hilarious satire but sadly I know typed this with a straight face.

> i wish you luck... i am done

...did you ever start?
