### ISSUE TITLE
BaseBarSeries and CachedIndicator are not working good in multi-thread mode

### ISSUE THREAD

**Issue by GxtPerfectoM** [ta4j/ta4j#609]
Due to their use of inner lists and some manipulations on the data these two data structures are not working good in multi-thread mode.

In BaseBarSeries, when using the getValue, there is a lot of other things going on, including the bars list resizing and other stuff - This should not be in base class - Only in advanced implementation.

In CachedIndicator, accessing the cache from multiple threads causes problems.

**Comment by team172011** [comment]
Helllo,

the is not a bug. The classes are not annoted as thread safe

**Comment by Viserius** [comment]
Hey @GxtPerfectoM
I ran across the same problem at my end.
Although this is not how the library was meant to be used, you can easily circumvent the problem.
The issue with concurrent access is caused by the fact that the ArrayList's size is continuously be updated (and flushed).
An easy fix is to change the CachedIndicator's behaviour by creating the ArrayList by specifying its initialization size, such that it is always large enough.

I.e.:
`private final List<T> results;` becomes `private List<T> results;`
```
    public CachedIndicator(BarSeries series) {
        super(series);
        results = new ArrayList<>(series.getBarCount());
    }
    public CachedIndicator(Indicator<?> indicator) {
        this(indicator.getBarSeries());
        results = new ArrayList<>(indicator.getBarSeries().getBarCount());
    }
```
worked like a charm for me. I won't create a PR since this only solves the problem when you pass it a BarSeries of which you know the size beforehand.

**Comment by nimo23** [comment]
>The issue with concurrent access is caused by the fact that the ArrayList's size is continuously be updated (and flushed).

Really? If so, then maybe we should use `results = new ArrayList<>(series.getMaximumBarCount());` only if `maximumBarCount` is defined by the user and does not default to `Integer.MAX_VALUE`:

```
public CachedIndicator(BarSeries series) {
        super(series);
        int limit = series.getMaximumBarCount;
        results = limit == Integer.MAX_VALUE ? new ArrayList<>(limit) : new ArrayList<>();
    }
    public CachedIndicator(Indicator<?> indicator) {
        this(indicator.getBarSeries());
        int limit = indicator.getBarSeries().getMaximumBarCount;
        results = limit == Integer.MAX_VALUE ? new ArrayList<>(limit) : new ArrayList<>();
    }
```

If this improves the caching situation, then we should create a PR with the above solution, or?


Btw, there java collection types which are thread safe AND bounded or unbounded (this means it acts as a circular buffer without the need to manage it in ta4j):

```
// thread safe bounded and unbounded queues: 
ArrayBlockingQueue` or `LinkedBlockingQueue
```

**Comment by Viserius** [comment]
Yes, really. When the data structure does not need to be resized, the caching works flawlessly on concurrent applications (both for initialized and non-initialized values).
Yet, it would be possible that 2 threads try to obtain the same uncached value, meaning they still compute the same value twice before storing it in the cache. Still, I feel this is not a problem for larger applications in which the cache gives an enormous performance boost.

A full disclaimer is that I am not much involved in this project, and simply tweaked it for my own use case. Initializing the capacity works if the size is known at the start. If you initialize it with a BarSeries of 10, add new bars, and concurrently try to access index 11, it needs to be resized and the solution does not work. It is why I mentioned this approach is very application-specific, but in my case and I think many others, it works "good enough". 

The solution you mentioned will work under the condition I described. Additionally, it actually increases performance by a lot. Because every time the structure is resized, the entire cache is flushed, requiring all values to be computed again. This prevents that from happening.

Lastly, you mention ArrayBlockingQueue and LinkedBlockingQueue. I am not familiar with those, but it seems the ArrayBlockingQueue cannot be resized, and the LinkedBlockingQueue cannot access a value based on index. I thought about replacing the ArrayList with a HashMap or something as well, but this would mean access changes from O(1) to O(log n)
