### ISSUE TITLE
[BUG] (maybe) RSI does not work correct

### ISSUE THREAD

**Issue by michaelBielang** [ta4j/ta4j#615]
**I have checked existing issues and wiki**
- [x] I could not find similar [issues](https://github.com/ta4j/ta4j/issues?utf8=%E2%9C%93&q=)
- [x] I could not find a solution in the [wiki](https://ta4j.github.io/ta4j-wiki/) or [faq section](https://ta4j.github.io/ta4j-wiki/FAQ.html)

**Describe the bug**

When init RSI with a 5 bar count and a series with 31 elements like this:

        RSIIndicator rsiIndicator = new RSIIndicator(new ClosePriceIndicator(series), 5);

and printing it with a timeFrame = 30

        for (int i = 0; i < timeFrame; i++) {
            System.out.println(rsiIndicator.getValue(i));
        }

it displays:

```
0
100
100
37.432093729284910197021341690625
20.719478191865555267881519548536
42.237865264527015637538832844100
42.736768731245623815538875415665
37.104884741689388203102840006839
33.754950167026280444935828128246
25.729113059232390193576668174109
35.508788656422222434654548260598
73.415742559244448598056379807535
77.886313265825882542587530653714
74.437080201479875489211558721033
64.291054957391883812797766461260
57.239577153318635216182407884540
28.341204630870278723886760101396
38.415208685894870278980801502224
48.520760147503720970040399319620
42.223896045824884677780205364780
60.206276023524579218003337482263
53.657476593311415271347993879496
48.570277220246207597491380798750
62.538901667378554584643926608746
64.003473394159998141739990652527
84.048524316585086550777526779095
82.784301210268590229966666253786
87.597406260507423218100875948735
87.840413548619902932247389418605
68.859467324213432320633739181943
62.850979999103943933989043351353
```

**Expected behavior**
The first 5 values should be 0

I have tested it with an integrated Matlab function and this also resultsthat the first five values are 0.
Also TradingView does not display RSI for the first 5 days.

**Comment by chaithanya3050** [comment]
Seems like this is because of RSI using a multiplier which makes it similar to Exponentials RSI. I also faced this same issue and after removing the multiplier I was able to produce proper output.

**Comment by krswin** [comment]
@chaithanya3050 Can you please give example how did you solve this bug? thanks.

**Comment by chaithanya3050** [comment]
@krswin, currently in the `RSIIndicator` for calculating average gain and loss, `MMAIndicator` is being used which is causing the multiplier `1.0D / (double)barCount` to be used because of which I'm not getting proper results as calculated in excel. When I replaced `MMAIndicator ` with `SMAIndicator`  and created a new Indicator my results matched with excel results.

**Comment by team172011** [comment]
Hi @chaithanya3050 @krswin thank you for reporting this issue. Compared to your excel/trading view results, how big are the deviations after giving this indicator a warm up period from lets say 10 ticks?

> When I replaced MMAIndicator with SMAIndicator and created a new Indicator my results matched with excel results.

Having a first look I would also say using SMA instead of MMA would make sense. 

Following [this formula](https://school.stockcharts.com/doku.php?id=technical_indicators:relative_strength_index_rsi) a start up of `barCount` bars is necessary and would also explain the first values beeing zero in other calculations
