### ISSUE TITLE
enhance "JustOnceRule"

### ISSUE THREAD

**Issue by nimo23** [ta4j/ta4j#64]
**JustOnceRule** should assert that a rule is fired only one time and then never again. It should behave like the rule for "CrossedUp/CrossedDownRule" (which only fires one time as soon as the rule is satisfied and then never again).

However, I cannot put a rule within JustOnceRule, which I want to fire only one time. So for example, this is actually not possible:

```
// Fires only one time as soon as the actual value is higher than its two previous values.
// Even if the "next value" is also higher than its 2 previous values, 
// the rule is no more fired, because of JustOnceRule.
new JustOnceRule(isRisingRule(2));
```

Would be nice to enhance the "JustOnceRule" to made the above example possible.

**Comment by team172011** [comment]
> "CrossedUp/CrossedDownRule" (which only fires one time as soon as the rule is satisfied and then never again).

That is not correct. `CrossedUP/CrossedDownRule ` fires **every time** when the value of `indicator1` crosses up/down the value of `indicator2`

If i have understand you correct you can reach your plan without enhance the rule, but by adding the `JustRunceRule` via **.and()** conjunction to the rule you want to be satisfied just the first time, like:

`Rule myJustOnceRule = new CrossedUpIndicatorRule(indicator1, indicator2).and(new JustOnceRule())`

**Comment by TheCookieLab** [comment]
`Rule myJustOnceRule = new CrossedUpIndicatorRule(indicator1, indicator2).and(new JustOnceRule()) `

If I understand the OP requirement's correctly this only works on the first invocation. Let's say the first time around the CrossedUpIndicatorRule part returns false, and the JustOnceRule returns true. We get an overall false and everything is working as expected.

The second time around, the CrossedUpIndicatorRule returns true, but the JustOnceRule returns false (since it's already fired in the past). In this case, we want the overall expression to return true since this is the first time the subject rule (CrossedUpIndicatorRule) is satisfied. Unfortunately this time (and all subsequent times) we get an overall false.

**Comment by team172011** [comment]
Ah, i see -.- . 
So @nimo23 approach is correct

**Comment by nimo23** [comment]
Thanks.

**Comment by team172011** [comment]
I accidentially pushed to develop branch, but you can find the new rule from @TheCookieLab there.
