### ISSUE TITLE
`BarSeriesManager#run` with disabled caching

### ISSUE THREAD

**Issue by nimo23** [ta4j/ta4j#829]
Currently, when using `BarSeriesManager#run`, indicator values calculated while running the strategy within a backtest can be cached. Thus, running dozens of strategies will increase the overall memory (java heap) even if I do not need those indicator values afterwards. 

Would be nice to provide a property (e.g. `disableCache`) to have a `BarSeriesManager#run` **which does not cache**. Does anyone have an idea how to do that? 

- We can set those indicator values  (calculated by a strategy) to `null` after the `BarSeriesManager#run` created its `tradingRecord`. 
- Another alternative is to clear the cache from within the `BarSeriesManager#run` by a new method  `clear()`. 
- But a more elegant solution would be to disable the cache while backtesting (e.g. `BarSeriesManager#run(boolean disableCache,..)`) . Maybe this would be only possible after https://github.com/ta4j/ta4j/issues/608 is solved?

For backtesting different strategies, caching (indicator) values does not make sense, does it?

**Comment by johnthetireless** [comment]
I don't know how one would disable caching at the bar series manager level.
I might be able to help with your (real or potential) memory problem, though.

If you create your strategies and keep them in a list or map,
then run each, they will keep transitive references to the indicators and you could experience memory issues.
This is the obvious way to do it; I'm sure I would do this way until there were memory issues.

If you create your strategies just before you run them, you should be able to keep the trading record;
the strategy and its references to rules and then to indicators will become candidates for garbage collection.

Rather than:

    List strategies = createStrategies(); // the indicator array lists are empty here	
											// they will get filled below
											// they will not be GC'ed until "strategies" goes out of scope
	
	for ( Strategy s : strategies ) {
		tradingRecord = mamager.run(s);		// the indicator lists get populated here
	}
	
Something like:

	Map<String, TradingRecord> records = new HashMap<>();
	for ( int i = 0; i < numStragies; i++ ) {
		Strategy s = createStrategy(i);
		tradingRecord = mamager.run(s);
		records.put(s.name(), tradingRecord);
	}

Something as simple as createStrategy(i) might not work in general.
But this is the idea, I think.  Create a strategy, use it and move on.  

The values cached by the indicators used by strategy S are necessary until S is finished its run.
Then they are garbage.  
It might be possible to use the same indicator(s) in multiple strategies; you would need to careful how you create the strategies then.
I wouldn't bother.  I would recreate indicators for each strategy.

I agree with idea behind #608, but some things will always need to be cached.  
Recursive calculations in particular are not reasonable without caching.
This is just as true when we back test as when we use live data.

I hope this helps.

**Comment by nimo23** [comment]
Thanks for trying to help, but in my case, I don' t have a memory problem because I do it already similar as you described. However, that's more a walkaround-solution, thus it would be better to handle that within the lib directly, if possible. 

I don't talk about recursive calculations (which need short term cachings), I talk about general caching and disabling this within the `BarSeriesManager#run`.

**Comment by nimo23** [comment]
>I don't think ta4j should be responsible for making sure programmers use Java correctly to avoid misuse of its strategies and indicators. If you believe it should, I will simply say I disagree. 

I think ta4j **should be responsible for its memory consumption**, especially when using cached indicators **behind the scene** through the `barSeriesManager.run() `without clearing it afterwards or without having the possibility to disable or clear it manually. The user does not expect that after `barSeriesManager.run()` values are cached and are kept into the memory as long as indicator instances are alive. Yes, another possibility would be to set it to null, but then the user must know that those indicator values are cached by ta4j behind the scene even if the user does not want this caching. And by the way, why one should set an indicator to null only to clear its cache..if the user does not need the cache, caching should be disabled from the beginning.

**Comment by johnthetireless** [comment]
I still disagree, but I don't think I can convince you.   The BarSeriesManager.run method neither creates nor caches indicators or strategies.  Its clients control the lifetimes of those things.  If they do things right there is no problem to be solved.

I don't think ta4j should encourage people to do things that will tie up resources though.  This does that.  

    default Strategy chooseBest(BarSeriesManager manager, TradeType tradeType, List<Strategy> strategies) {

To do the "right thing" as we discussed above, I created and ran some strategies (a large number ; it worked well)
I created each one by one in a loop, running each one and letting it go out of scope; the JVM did the garbage collection. No problem.

I had to take the default method above apart to compare the trading records I collected.   It only a dozen lines of code or so. 
Other than that, everything worked quite well.  

The fix to ta4j is to break this method apart and present its function in a way that does not force the user to create a list of strategies.  I think.  I certainly don't think chasing a special form of caching is sensible here.  I will say no more.

**Comment by nimo23** [comment]
If we provide a solution for https://github.com/ta4j/ta4j/issues/608, then this issue can be easily solved without any modification in `BarSeriesManager`, because then we are able to put _uncached versions of indicators_ into the running Strategy. Thus, I will close this issue as it can be seen as duplicate.

**Comment by johnthetireless** [comment]
I'm afraid there is no such thing as an uncached version of an EMA,   Or OBV.  There aren't very many recursive indicators in ta4j but they cannot be reasonably implemented with no cache.     Things will be less likely to be a problem if you can create strategies with uncached MACD and stuff like that, absolutely.  Fewer array lists.  The 2 EMAs the MACD is based on will be cached, or your system will not work.  I really will say no more at this point.
