### ISSUE TITLE
How do you install ta4j on Linux?

### ISSUE THREAD

**Issue by hhashim1** [ta4j/ta4j#852]
Hi,

I need some help with installing the ta4j library in Linux via Terminal. I am not savvy with Linux and do not know how I can accomplish this.

Any help would be greatly appreciated.

Thank you!

**Comment by team172011** [comment]
I am not sure what you mean with installing the library via terminal. You can use this library in a maven project like described in the readme or wiki. Basic knowledge of java, maven is required.

Otherwise to make ta4j available for maven on the current machine using git and maven:

```
git clone https://github.com/ta4j/ta4j.git
cd ta4j
mvn clean install
```

or `mvn clean Package`  for creating the .jar
