### ISSUE TITLE
How to manage stop loss orders ?

### ISSUE THREAD

**Issue by gelhaimer** [ta4j/ta4j#922]
**I have checked existing issues and wiki**
- [X] I could not find similar [issues](https://github.com/ta4j/ta4j/issues?utf8=%E2%9C%93&q=)
- [X] I could not find a solution in the [wiki](https://ta4j.github.io/ta4j-wiki/) or [faq section](https://ta4j.github.io/ta4j-wiki/FAQ.html)

If possible provide a **[minimal working example](https://stackoverflow.com/help/mcve)**!

ta4j is the most complete ta library I found as far as indicators are concerned. Awesome job !

I was considering using it until I met the strategy implementation. This one brought a lot of questions to me about entry and exit rules.

Actually, the exist rule was what really buged me.

When trading, the exist rule is usally a mix between a stop loss and a take profit orders which are placed according to a predifined risk ratio.

Let's say I'm willing to have a 1:1 risk ratio. Which means I'll risk as much as I'm targeting to profit. 
To defined my profit target, I'll first set my stop loss. There are several ways to do so, but let's say the PSAR will be used.
When an entry signal is detected, my exist rule should be both:
- a stop loss order at the PSAR value
- a take profit order at the current price + (current price - PSAR value)

ta4j makes possible to implement such a rule. But unfortunately, it won't work on a trading bot.

Let's say the bot is trading on the 1h time frame. The exist rule will be evaluated at the next received bar (= the next hour). 
The exit decision will be taken too late risking way more than the risk management strategy allows.
The only way to comply with the risk management is to place orders which will be executed directly by the broker.

What I've considered was to ignore the exist rule (or use it for short entry signals) and create orders I'll push to the broker according to the entry signal.
However, it makes the strategy unable to be backtested as it does not take into account the possibility to have stop loss order.

I considered using the exist rule to simulate the stop loss order on backtesting. But doing so would result in having at least 2 implementations of the same strategy for :
- live trading which will only detect entry signals
- backtesting which will detect entry signals as the live trading does but with an hack on exist rule to simulate stop loss and take profit executions (making the use of exit rule for short position impossible)

What I would have expected would be to have one single strategy and being able to use it in both backtesting and live trading contexts.

My question is then : how do you manage stop loss (and take profit) within a single strategy ?

**Comment by gelhaimer** [comment]
> would it be sufficient to add the last recently price to the latest bar? This is actually possible. So that your strategy executes on the latest bar..the latest bar can be filled with prices what ever you want..

Problem with this approach is that it will mixes the order execution with the actual strategy.

The responsibility of the strategy is to detect entries and the exists as take profit / stop loss according to the risk management strategy. How those order are executed should not depend on how the strategy implements these concepts.

For instance, a stop loss order can be a trailling stop loss. Which mean that stop loss level will move according to the market price.
How this work is independent of the strategy. The strategy should only tell whether we are going short or long and at what risk whether. It should not be redifined within strategies, IMHO.

With the current implementation, it would mix both concepts of entry detection and order execution although order execution is not directly bound to the strategy.

It migh be interesting to see if the strategy could provide an `EntrySignal` instead of an exist rule. The trading record could then deal with this EntrySignal and be responsible to actualy execute it or not (ex: limited to one opened position).

This could look like 

```
    interface Strategy {

        String getName();
        Optional<EntrySignal> getEntrySignal() // If no signal, then nothing to trade
        ...
    }

    class EntrySignal {
        PositionType positionType;
        Num stopLoss;
        Num takeProfit;
        Num size;
    }

    enum PositionType {
        LONG, SHORT
    }
```

It could let us articulate between a trading record simulating the broker and a pure strategy which could work in back testing as well as in automated trading.

I hope it was clear enough

**Comment by TheCookieLab** [comment]
Why not evaluate the strategy's `shouldExit` multiple times for the current bar? For example if you're using the 1hr chart, you can poll your bar series source every 10 minutes for the latest OHLC data and evaluate your strategy's entry and exit criteria each time. 

How timely your exit decision then becomes a function of how frequently you poll for the bar data. The `public void addBar(Bar bar, boolean replace)` has the `replace` param to help update the last bar.

**Comment by team172011** [comment]
I think the answer from @TheCookieLab is a solution to this problem:
>Let's say the bot is trading on the 1h time frame. The exist rule will be evaluated at the next received bar (= the next hour).
The exit decision will be taken too late risking way more than the risk management strategy allows.

If you are using 1h bars, you are only able to evaluate at the end of each our, because this is the earliest point the ohlcv values are correctly and completely calculated. This is not an issue of the ta4j lib, it would be the same case if you would look at a chart using this data - every hour a new bar would appear. 

@gelhaimer if you want your trading bot to react earlier, you have to feed it with shorter intervals like 10 minute bars. But also this would mean, your bot is only able to create and evaluate new signals every 10 minutes

**Comment by marsteff** [comment]
@team172011 i think there is no problem by updating the last bar.

My bot is feeded through a price-stream which comes from a broker. That means, every second i update the last candle and recalculate the indicators and show, if i have to enter or exit a trade (and that for 40 instruments at the same time).
I think especially for the exit it is important to check the actual closing price and if i have to close the trade (with a stoploss or somethin like this). But also for the enter it is important, because you don´t get the optimal entry-point.

The con is, that sometimes you have fake signals (like when your strategy enter when RSI crossing down 70), but you can also have something like this when you trade at the finished candle.

Do you only trading on finished candles?

**Comment by team172011** [comment]
The advantage on trading on unfinished bars is that you can generate signals as early as possible. For instance if you are just waiting for some kind of maximum or minimum to enter or exit the market. 
But it could be dangerous if you have a more complex indicators or strategies. Or even simpler cases are possible, because most indicators are based on the close price as default: Imagine a dummy strategy "BUY if close price is over > 10 and SELL if close price is < 5". If you update your last bar several times you could generate several buy or several buy and sell signals for the same index:

- `barSeries.addPrice(11)` >> **BUY**
- `barSeries.addPrice(4 )` >> **SELL**
- `barSeries.addPrice(12)` >> **BUY**
- `barSeries.addPrice(11)` >> **BUY**
