### ISSUE TITLE
Requirements for granting merge permission etc.

### ISSUE THREAD

**Issue by nimo23** [ta4j/ta4j#966]
We should have **minimum requirements** that must be met before someone is granted the right to `merge PRs` or `edit/close other PRs` or `edit/close other Issues`.

Objective evaluation like:

- The person must have made **at least 180 commits** on this project before @team172011 will give the person permission to `merge PRs` or `edit/close other PRs` or `edit/close other Issues`. These commits must be **standalone** commits, i.e. not re-commiting commits from other users.

This is an **objective measure** which at least proves that the person has continuously and successfully contributed to the project in the past.  What do you think?

The rights/permissions who can merge, etc. must be transparent and objective. 

We should also write these **minimum requirements** in our https://github.com/ta4j/ta4j/blob/develop/CODE_OF_CONDUCT.md.

**Comment by team172011** [comment]
I am the only active member of the ta4j organization since over six years. Most contributors are only working a short time on this project and that is totally fine. Most contributors are only focused on a specific feature or fix and do not care for other topics or further issues with their contributions and this is also totally fine. But this means I will not grant any permission to anybody only based on metrics like commits or pull request.
If someone wants to support ta4j in more than being a contributor he can just ask for it. For me it is important to have a common vision of how to contribute to this library.
